### ISSUE TITLE
Add Plex Streaming Script to DN

### ISSUE THREAD

**Issue by bakerboy448** [Go-Lift-TV/discordnotifier-client#17]
https://discordnotifier.com/scripts/discordnotifier_plexStreaming_win-linux.py

needs to always be listening

The two other scripts (snapshot and sessions) are one offs and thus are best via cron.  The streaming script must always be running.  Ideally this will solve the CPU/RAM not being updated.

**Comment by austinwbest** [comment]
This would also need the settings conf & as for the cron based ones, nothing a timer can't handle
